AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Authentication Lambda Function

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    Environment:  
      Variables: 
        POWERTOOLS_SERVICE_NAME: lambda_auth
        LOG_LEVEL: INFO
        LOG_EVENT: true
  Api:
    Cors:
      AllowMethods: "'OPTIONS,POST,GET'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  SharedLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: shared/
      CompatibleRuntimes:
        - python3.9
  # KMSKey: 
  #   Type: AWS::KMS::Key
  #   Properties:  
  #     EnableKeyRotation: True
  #     KeyPolicy:

  AuthFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Layers:
        - !Ref SharedLayer
      Handler: src/app.handler
      Runtime: python3.9
      Tracing: Active
      Architectures:
        - x86_64
      Events:
        All: 
          Type: Api
          Properties:
            Path: /{path+}
            Method: ANY
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: UserTable
      AttributeDefinitions:
        - AttributeName: "username"
          AttributeType: S
      KeySchema:
        - AttributeName: "username"
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      
        
